#!/bin/bash
#
#Andmbebaasi loomise skript
kasutaja=$1
parool=$(tr -cd '[:alnum:]' < /dev/urandom | fold -w30 | head -n1)
echo "password=$parool" > .parool.tmp
echo "$parool" > .parool2.tmp

if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 Kasutajanimi"
else

echo "Palun sisesta Andmebaasi root kasutaja parool: "
read dbrootpass

#################################################
echo "[mysql]" > /home/$kasutaja/.my.cnf
echo "user=$kasutaja" >> /home/$kasutaja/.my.cnf
paste .parool.tmp >> /home/$kasutaja/.my.cnf
echo "[mysqladmin]" >> /home/$kasutaja/.my.cnf
echo "user=$kasutaja" >> /home/$kasutaja/.my.cnf
paste .parool.tmp >> /home/$kasutaja/.my.cnf
#################################################

echo "Sisesta andmebaasi nimi"
read dbnimi
dbname=$kasutaja_$dbnimi

for dbpass in $(cat .parool2.tmp)
do
mysql -uroot -p$dbrootpass -e "create database $dbname ; GRANT ALL PRIVILEGES ON $dbname.* TO $kasutaja@localhost IDENTIFIED BY '$dbpass'"
done

rm .parool.tmp
rm .parool2.tmp
fi
