#!/bin/bash
#
#Andmbebaasi loomise skript
kasutaja=$1
dbname=$2
kp=$(date +"%Y-%m-%d.%H-%M")

if [ $# -ne 2 ]; then
	echo "Kasutusjuhend: $0 Kasutajanimi Andmebaasinimi"
elif [ ! -e /home/$kasutaja/.my.cnf ]; then

sh kasutajad_db

else

mysqldump -u$kasutaja $dbname > /home/$kasutaja/$kp.$dbname.backup.sql
mkdir /mysql_backup
tar -czvf /home/$kasutaja/$kp.$dbname.backup.sql.tar.gz
mv /home/$kasutaja/$kp.$dbname.backup.sql.tar.gz /mysql_backup/
rm /home/$kasutaja/$kp.$dbname.backup.sql

fi
