#!/bin/bash
#
#Kasutajale public veebilehe lisamine
#
#
kasutaja=$1
public=/home/$kasutaja/public
ip=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 Kasutajanimi"
elif [ !-d "$public" ]; then
		mkdir $public
		chmod -R 751 $public
		echo "<html><body>Tere, $kasutaja</body></html>" > $public/index.html
		sed -i 's/public_html/public/g' /etc/apache2/mods-available/userdir.conf
		a2enmod userdir
		service apache2 restart
else
echo "Kaust /home/$kasutaja/public juba eksisteerib!"
echo "Kontrollin õigusi!"
chmod -R 751 $public
if [ $? -eq 0 ]; then
	echo "Loodud avalik veebileht kasutajale $kasutaja"
	echo "Leiad selle järgmiselt aadressilt: http://$ip/~$kasutaja/index.html"
else
	echo "Esines probleem veebilehe loomisel kasutajale $kasutaja"
	echo "Veakood: $?"
fi
fi

