#!/bin/bash
#
#Kasutajate lisamine
#
#

if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 Kasutajanimi"
else

kasutaja=$1
ip=$(ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')

mkdir /home/$kasutaja/public
chmod 751 /home/$kasutaja/public
echo "<html><body>Tere, $kasutaja</body></html>" > /home/$kasutaja/public/index.html
sed -i 's/public_html/public/g' /etc/apache2/mods-available/userdir.conf
a2enmod userdir
service apache2 restart

if [ $? -eq 0 ]; then
	echo "Loodud avalik veebileht kasutajale $kasutaja"
	echo "Leiad selle järgmiselt aadressilt: http://$ip/~$kasutaja/index.html"
	ls -la /home/$kasutaja
else
	echo "Esines probleem $kasutaja lisamisega."
	echo "Veakood: $?"
fi
fi

