#!/bin/bash
#
#
if [$# -ne 1 ]; then
	echo "Kasutusjuhend: $0 failinimi"
else
	failinimi=$1
if [ -f $failinimi -a -r $failinimi ]; then
	echo "Kõik korras"
	for rida in $(cat $failinimi)
		do
			kasutajanimi=$(echo="$rida" | cut -f1 -d:)
			sh lisa_kasutaja $kasutajanimi
			echo "$rida"

		done
		echo "$rida" | chpasswd
else
	echo "probleem failiga $failinimi"
fi
fi
