#!/bin/bash
#
clear
tput setaf 5
echo "Tere tulemast LEMP stack installmenüüsse."
echo "Tegevuste valik:"
tput setaf 6
echo "1 - Paigalda Nginx"
echo "2 - Paigalda MySQL"
echo "3 - Paigalda PHP"
echo "4 - Paigalda PhpMyAdmin"
echo "5 - Paigalda Wordpress"
echo "6 - Paigalda kõik"
echo "7 - Välju menüüst"
tput setaf 5
echo -n "Palun vali oma tegevus: "
read asi
tput sgr0

nginx=$(dpkg-query -W -f='${Status}' nginx 2>/dev/null | grep -c "ok installed")
phpcli=$(dpkg-query -W -f='${Status}' php-cli 2>/dev/null | grep -c "ok installed")
mysql=$(dpkg-query -W -f='${Status}' mysql-server 2>/dev/null | grep -c "ok installed")
php=$(dpkg-query -W -f='${Status}' php-fpm 2>/dev/null | grep -c "ok installed")
mcrypt=$(dpkg-query -W -f='${Status}' php-mcrypt 2>/dev/null | grep -c "ok installed")
phpmysql=$(dpkg-query -W -f='${Status}' php-mysql 2>/dev/null | grep -c "ok installed")
phpcurl=$(dpkg-query -W -f='${Status}' php-curl 2>/dev/null | grep -c "ok installed")
pma=$(dpkg-query -W -f='${Status}' phpmyadmin 2>/dev/null | grep -c "ok installed")

if [ $asi = 1 ]; then
apt --assume-yes update
apt --assume-yes upgrade
	if [ $nginx -eq 1 ]; then
	echo "Nginx on juba paigaldatud!"
	exit
	else
	echo "Nginx paigaldamine..."
	apt --assume-yes install nginx
	echo "Nginx paigaldatud!"
	fi
elif [ $asi = 2 ]; then
echo "Sisesta MySQL root kasutaja parool: "
read dbpass
apt --assume-yes update
apt --assume-yes upgrade
	if [ $mysql -eq 1 ]; then
        	echo "MySQL on juba paigaldatud!"
        	exit
        else
	echo "MySQL paigaldamine..."
	echo "mysql-server mysql-server/root_password password $dbpass" | debconf-set-selections
	echo "mysql-server mysql-server/root_password_again password $dbpass" | debconf-set-selections
	apt --assume-yes install mysql-server
	#mysql_secure_installation
	mysql_install_db
	mysql -uroot -p$dbpass -e "DROP DATABASE test"
	mysql -uroot -p$dbpass -e "DELETE FROM mysql.user WHERE User='root' AND NOT IN ('localhost', '127.0.0.1', '::1')"
	mysql -uroot -p$dbpass -e "DELETE FROM mysql.user WHERE User=''"
	mysql -uroot -p$dbpass -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
	mysql -uroot -p$dbpass -e "FLUSH PRIVILEGES"
	echo "MySQL paigaldatud"
	fi
elif [ $asi = 3 ]; then
apt --assume-yes update
apt --assume-yes upgrade
	if [ $php -eq 1 ] && [ $mcrypt -eq 1 ] && [ $phpmysql -eq 1 ] && [ $phpcli -eq 1 ] && [ $phpcurl -eq 1 ]; then
                echo "PHP ja kõik vajalikud moodulid on juba paigaldatud!"
                exit
        else
        echo "PHP paigaldmine..."
        apt --assume-yes install php-fpm php-mcrypt php-mysql php-cli php-curl
	sed -i s/\;cgi\.fix_pathinfo\s*\=\s*1/cgi.fix_pathinfo\=0/ /etc/php/7.0/fpm/php.ini
	service php-fpm restart
	phpenmod mcrypt
        echo "PHP ja vajalikud moodulid paigaldatud"
        fi

elif [ $asi = 4 ]; then
echo "Sisesta MySQL root kasutaja parool: "
read dbpass
apt --assume-yes update
apt --assume-yes upgrade
	if [ $pma -eq 1 ] && [ $nginx -eq 1 ] && [ $mysql -eq 1 ] && [ $php -eq 1 ] && [ $mcrypt -eq 1 ] && [ $phpmysql -eq 1 ] && [ $phpcli -eq 1 ] && [ $phpcurl -eq 1 ]; then
                echo "PhpMyAdmin on juba paigaldatud!"
                exit
        else
        echo "vajalike pakettide paigaldmine..."
	echo "mysql-server mysql-server/root_password password $dbpass" | debconf-set-selections
	echo "mysql-server mysql-server/root_password_again password $dbpass" | debconf-set-selections
        apt --assume-yes install nginx mysql-server php-fpm php-mcrypt php-cli php-curl php-mysql phpmyadmin
        #mysql_secure_installation
        mysql_install_db
        mysql -uroot -p$dbpass -e "DROP DATABASE test"
        mysql -uroot -p$dbpass -e "DELETE FROM mysql.user WHERE User='root' AND NOT IN ('localhost', '127.0.0.1', ':$
        mysql -uroot -p$dbpass -e "DELETE FROM mysql.user WHERE User=''"
        mysql -uroot -p$dbpass -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
        mysql -uroot -p$dbpass -e "FLUSH PRIVILEGES"
	sed -i s/\;cgi\.fix_pathinfo\s*\=\s*1/cgi.fix_pathinfo\=0/ /etc/php/7.0/fpm/php.ini
        service php-fpm restart
        phpenmod mcrypt
	echo "LEMP stack & PhpMyAdmin paigaldatud"
        fi

elif [ $asi = 5 ]; then
echo "Sisesta soovitud WordPress andmebaasi nimi: "
read dbname
echo "Sisesta soovitud WordPress kasutaja nimi: "
read dbuser
echo "Sisesta soovitud andmebaasi parool: "
read dbpass
echo "Sisesta MySQL admin kasutaja nimi: "
read dbroot
echo "Sisesta MySQL admin kasutaja parool: "
read dbrootpass
apt --assume-yes update
apt --assume-yes upgrade
	if [ $nginx -eq 1 ] && [ $mysql -eq 1 ] && [ $php -eq 1 ] && [ $mcrypt -eq 1 ] && [ $phpmysql -eq 1 ] && [ $phpcli -eq 1 ] && [ $phpcurl -eq 1 ]; then
		echo "LEMP stack on juba paigaldatud, jätkan WordPressi paigaldamisega!"
	else
		echo "LEMP stack paigaldamine."
	echo "mysql-server mysql-server/root_password password $dbrootpass" | debconf-set-selections
        echo "mysql-server mysql-server/root_password_again password $dbrootpass" | debconf-set-selections
        apt --assume-yes install nginx mysql-server php-fpm php-mcrypt php-cli php-curl php-mysql
        #mysql_secure_installation
        mysql_install_db
        mysql -uroot -p$dbrootpass -e "DROP DATABASE test"
        mysql -uroot -p$dbrootpass -e "DELETE FROM mysql.user WHERE User='root' AND NOT IN ('localhost', '127.0.0.1', ':$        mysql -uroot -p$dbpass -e "DELETE FROM mysql.user WHERE User=''"
        mysql -uroot -p$dbrootpass -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
        mysql -uroot -p$dbrootpass -e "FLUSH PRIVILEGES"
        sed -i s/\;cgi\.fix_pathinfo\s*\=\s*1/cgi.fix_pathinfo\=0/ /etc/php/7.0/fpm/php.ini
        service php-fpm restart
        phpenmod mcrypt
        echo "LEMP stack paigaldatud"
	fi

echo "WordPressi paigaldmine..."
cd /var/www/html/
curl -O https://wordpress.org/latest.tar.gz
tar -zxvf latest.tar.gz
cd wordpress
cp wp-config-sample.php wp-config.php
sed -e “s/database_name_here/$dbname/g” wp-config.php
sed -e “s/username_here/$dbuser/g” wp-config.php
sed “s/password_here/$dbpass/g” wp-config.php
mkdir -p wp-content/uploads
chmod 755 wp-content/uploads
rm latest.tar.gz
cd ~
mysql -u$dbroot -p$dbrootpass -e "create database $dbname; GRANT ALL PRIVILEGES ON $dbname.* TO $dbuser@localhost IDENTIFIED BY '$dbpass'"
echo "WordPress paigaldatud"

elif [ $asi = 6 ]; then

echo "Sisesta soovitud WordPress andmebaasi nimi: "
read dbname
echo "Sisesta soovitud WordPress kasutaja nimi: "
read dbuser
echo "Sisesta soovitud andmebaasi parool: "
read dbpass
echo "Sisesta MySQL admin kasutaja nimi: "
read dbroot
echo "Sisesta MySQL admin kasutaja parool: "
read dbrootpass
        apt --assume-yes update
	apt --assume-yes upgrade
	if [ $nginx -eq 1 ] && [ $mysql -eq 1 ] && [ $pma -eq 1 ] && [ $php -eq 1 ] && [ $mcrypt -eq 1 ] && [ $phpmysql -eq 1 ] && [ $phpcli -eq 1 ] && [ $phpcurl -eq 1 ]; then
		echo "LEMP stack on juba paigaldatud, jätkan WordPressi paigaldamisega!"
	else
                echo "LEMP, PMA ja WP paigaldamine"
        echo "mysql-server mysql-server/root_password password $dbrootpass" | debconf-set-selections
        echo "mysql-server mysql-server/root_password_again password $dbrootpass" | debconf-set-selections
        apt --assume-yes install nginx mysql-server php-fpm php-mcrypt php-cli php-curl php-mysql phpmyadmin
        #mysql_secure_installation
        mysql_install_db
        mysql -uroot -p$dbrootpass -e "DROP DATABASE test"
        mysql -uroot -p$dbrootpass -e "DELETE FROM mysql.user WHERE User='root' AND NOT IN ('localhost', '127.0.0.1', ':$        mysql -uroot -p$dbpass -e "DELETE FROM mysql.user WHERE User=''"
        mysql -uroot -p$dbrootpass -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
        mysql -uroot -p$dbrootpass -e "FLUSH PRIVILEGES"
        sed -i s/\;cgi\.fix_pathinfo\s*\=\s*1/cgi.fix_pathinfo\=0/ /etc/php/7.0/fpm/php.ini
        service php-fpm restart
        phpenmod mcrypt
	fi
cd /var/www/html/
curl -O https://wordpress.org/latest.tar.gz
tar -zxvf latest.tar.gz
cd wordpress
cp wp-config-sample.php wp-config.php
sed -e “s/database_name_here/$dbname/g” wp-config.php
sed -e “s/username_here/$dbuser/g” wp-config.php
sed “s/password_here/$dbpass/g” wp-config.php
mkdir -p wp-content/uploads
chmod 755 wp-content/uploads
rm latest.tar.gz
cd ~
mysql -u$dbroot -p$dbrootpass -e "create database $dbname; GRANT ALL PRIVILEGES ON $dbname.* TO $dbuser@localhost IDENTIFIED BY '$dbpass'"
echo "WordPress on paigaldatud!"
elif [ $asi = 7 ]; then
	exit
else
	./LEMP-install
fi
